name: Manual deploy
on:
  workflow_dispatch:
    inputs:
      app:
        description: "The app to deploy"
        required: true
        type: choice
        options:
          - flok
          - flok-admin
jobs:
  deploy-flok:
    if: ${{ github.event.inputs.app == 'flok'}}
    uses: ./.github/workflows/deploy.yaml
    with:
      app: flok
    secrets:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  deploy-flok-admin:
    if: ${{ github.event.inputs.app == 'flok-admin'}}
    uses: ./.github/workflows/deploy.yaml
    with:
      app: flok-admin
    secrets:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
