name: Manual deploy (production)
on:
  workflow_dispatch:
    inputs:
      app:
        description: "The app to deploy"
        required: true
        type: choice
        options:
          - flok
          - flok-admin
jobs:
  deploy-flok-staging:
    if: ${{ github.event.inputs.app == 'flok' && github.ref == 'refs/heads/staging' }}
    uses: ./.github/workflows/deploy.yaml
    with:
      module: flok
      heroku-app: flok-staging
    secrets:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  deploy-flok-admin-staging:
    if: ${{ github.event.inputs.app == 'flok-admin' && github.ref == 'refs/heads/staging' }}
    uses: ./.github/workflows/deploy.yaml
    with:
      module: flok-admin
      heroku-app: flok-admin-staging
    secrets:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
